class Urls:
    API = "https://api.steampowered.com"
    LOGIN = "https://login.steampowered.com"
    COMMUNITY = "https://steamcommunity.com"
    INVENTORY = "https://steamcommunity.com/inventory"
    MY_INVENTORY = "https://steamcommunity.com/my/inventory"
    MARKET = "https://steamcommunity.com/market"
    ACCOUNT = "https://store.steampowered.com/account"
    STORE = "https://store.steampowered.com"
    HISTORY = "https://steamcommunity.com/market/myhistory"
